const priceData = {
  Punjab: {
    vegetables: [
      { name: 'Apple gourd (Tinda)', price: 220 },
      { name: 'Beetroot', price: 100 },
      { name: 'Bitter gourd (Karela)', price: 125 },
      { name: 'Bottle gourd (Loki)', price: 85 },
      { name: 'Cabbage', price: 35 },
      { name: 'Carrot', price: 60 },
      { name: 'Capsicum', price: 95 },
      { name: 'Cauliflower', price: 60 },
      { name: 'Cucumber', price: 50 },
      { name: 'Eggplant', price: 60 },
      { name: 'Garlic', price: 220 },
      { name: 'Garlic (China)', price: 325 },
      { name: 'Ginger', price: 600 },
      { name: 'Green Chilli', price: 120 },
      { name: 'Lemon (China)', price: 190 },
      { name: 'Ladyfinger', price: 210 },
      { name: 'Onion', price: 104 },
      { name: 'Pea', price: 125 },
      { name: 'Potato', price: 45 },
      { name: 'Radish', price: 35 },
      { name: 'Spinach', price: 35 },
      { name: 'Tomato', price: 102 },
      { name: 'Turnip', price: 40 }
    ],
    fruits: [
      { name: 'Apple', price: 20 },
      { name: 'Banana', price: 25 },
      { name: 'Orange', price: 15 },
    ],
    crops: [
      { name: 'Wheat', price: 5 },
      { name: 'Rice', price: 10 },
      { name: 'Maize', price: 8 },
    ],
  },
  Sindh: {
    vegetables: [
      { name: 'Apple gourd (Tinda)', price: 220 },
      { name: 'Beetroot', price: 100 },
      { name: 'Bitter gourd (Karela)', price: 125 },
      { name: 'Bottle gourd (Loki)', price: 85 },
      { name: 'Cabbage', price: 35 },
      { name: 'Carrot', price: 60 },
      { name: 'Capsicum', price: 95 },
      { name: 'Cauliflower', price: 60 },
      { name: 'Cucumber', price: 50 },
      { name: 'Eggplant', price: 60 },
      { name: 'Garlic', price: 220 },
      { name: 'Garlic (China)', price: 325 },
      { name: 'Ginger', price: 600 },
      { name: 'Green Chilli', price: 120 },
      { name: 'Lemon (China)', price: 190 },
      { name: 'Ladyfinger', price: 210 },
      { name: 'Onion', price: 104 },
      { name: 'Pea', price: 125 },
      { name: 'Potato', price: 45 },
      { name: 'Radish', price: 35 },
      { name: 'Spinach', price: 35 },
      { name: 'Tomato', price: 102 },
      { name: 'Turnip', price: 40 }
    ],
    fruits: [
      { name: 'Apple', price: 22 },
      { name: 'Banana', price: 27 },
      { name: 'Orange', price: 17 },
    ],
    crops: [
      { name: 'Wheat', price: 6 },
      { name: 'Rice', price: 12 },
      { name: 'Maize', price: 10 },
    ],
  },
  KhyberPakhtunkhwa: {
    vegetables: [
      { name: 'Apple gourd (Tinda)', price: 220 },
      { name: 'Beetroot', price: 100 },
      { name: 'Bitter gourd (Karela)', price: 125 },
      { name: 'Bottle gourd (Loki)', price: 85 },
      { name: 'Cabbage', price: 35 },
      { name: 'Carrot', price: 60 },
      { name: 'Capsicum', price: 95 },
      { name: 'Cauliflower', price: 60 },
      { name: 'Cucumber', price: 50 },
      { name: 'Eggplant', price: 60 },
      { name: 'Garlic', price: 220 },
      { name: 'Garlic (China)', price: 325 },
      { name: 'Ginger', price: 600 },
      { name: 'Green Chilli', price: 120 },
      { name: 'Lemon (China)', price: 190 },
      { name: 'Ladyfinger', price: 210 },
      { name: 'Onion', price: 104 },
      { name: 'Pea', price: 125 },
      { name: 'Potato', price: 45 },
      { name: 'Radish', price: 35 },
      { name: 'Spinach', price: 35 },
      { name: 'Tomato', price: 102 },
      { name: 'Turnip', price: 40 }
    ],
    fruits: [
      { name: 'Apple', price: 25 },
      { name: 'Banana', price: 30 },
      { name: 'Orange', price: 20 },
    ],
    crops: [
      { name: 'Wheat', price: 8 },
      { name: 'Rice', price: 15 },
      { name: 'Maize', price: 12 },
    ],
  },
  balochistan: {
    vegetables: [
      { name: 'Apple gourd (Tinda)', price: 220 },
      { name: 'Beetroot', price: 100 },
      { name: 'Bitter gourd (Karela)', price: 125 },
      { name: 'Bottle gourd (Loki)', price: 85 },
      { name: 'Cabbage', price: 35 },
      { name: 'Carrot', price: 60 },
      { name: 'Capsicum', price: 95 },
      { name: 'Cauliflower', price: 60 },
      { name: 'Cucumber', price: 50 },
      { name: 'Eggplant', price: 60 },
      { name: 'Garlic', price: 220 },
      { name: 'Garlic (China)', price: 325 },
      { name: 'Ginger', price: 600 },
      { name: 'Green Chilli', price: 120 },
      { name: 'Lemon (China)', price: 190 },
      { name: 'Ladyfinger', price: 210 },
      { name: 'Onion', price: 104 },
      { name: 'Pea', price: 125 },
      { name: 'Potato', price: 45 },
      { name: 'Radish', price: 35 },
      { name: 'Spinach', price: 35 },
      { name: 'Tomato', price: 102 },
      { name: 'Turnip', price: 40 }
    ],
    fruits: [
      { name: 'Apple', price: 25 },
      { name: 'Banana', price: 30 },
      { name: 'Orange', price: 20 },
    ],
    crops: [
      { name: 'Wheat', price: 8 },
      { name: 'Rice', price: 15 },
      { name: 'Maize', price: 12 },
    ],
  },
  GilgitBaltistan: {
    vegetables: [
      { name: 'Apple gourd (Tinda)', price: 220 },
      { name: 'Beetroot', price: 100 },
      { name: 'Bitter gourd (Karela)', price: 125 },
      { name: 'Bottle gourd (Loki)', price: 85 },
      { name: 'Cabbage', price: 35 },
      { name: 'Carrot', price: 60 },
      { name: 'Capsicum', price: 95 },
      { name: 'Cauliflower', price: 60 },
      { name: 'Cucumber', price: 50 },
      { name: 'Eggplant', price: 60 },
      { name: 'Garlic', price: 220 },
      { name: 'Garlic (China)', price: 325 },
      { name: 'Ginger', price: 600 },
      { name: 'Green Chilli', price: 120 },
      { name: 'Lemon (China)', price: 190 },
      { name: 'Ladyfinger', price: 210 },
      { name: 'Onion', price: 104 },
      { name: 'Pea', price: 125 },
      { name: 'Potato', price: 45 },
      { name: 'Radish', price: 35 },
      { name: 'Spinach', price: 35 },
      { name: 'Tomato', price: 102 },
      { name: 'Turnip', price: 40 }
    ],
    fruits: [
      { name: 'Apple', price: 25 },
      { name: 'Banana', price: 30 },
      { name: 'Orange', price: 20 },
    ],
    crops: [
      { name: 'Wheat', price: 8 },
      { name: 'Rice', price: 15 },
      { name: 'Maize', price: 12 },
    ],
  },
};

export default JSON.stringify(priceData);


